TAGS = [
 "HOOK","SCENE_IT","SENSORY","INTERIORITY","SPECIFICITY","FACT_PRECISION",
 "SURPRISE_TIMING","ARTIFACT_FIRST","STRUCTURE","BRIDGE_CLARITY","TONE_MATCH",
 "PACE_CONTROL","VISUAL_HYGIENE","VISUAL_SYNC","HUMOR_TIMING","CONTRADICTION_FIX",
 "LOGIC_CLARITY","NUMBERS_GAME","SPOTLIGHT_EFFECT","PRIVILEGE_CHECK","METRICIFY_TIME",
 "CTA_HYGIENE","ANCHOR_TO_STORY","DELIVERY_HYGIENE","CURATION","ORIGIN_MOMENT",
 "COURAGE_EARNED","ESCALATION","PROGRESSION","TRANSLATION","ITCH_KILLER"
]
